name: CI for Node.js

on:
  push:                   # Pushes to main.
    branches: [ 'main' ]  
  pull_request:           # PRs to main.
    branches: [ 'main' ]
  workflow_dispatch:      # Manual trigger.
    inputs:
      pack-version:
        description: 'The version of pack to install'

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  container:
    if: ${{ github.event_name }}" == 'push'     # Blocks from running Containerize unless a push event.
    name: Containerize
    runs-on: ubuntu-latest
    needs: test           # depends on jobs.test to finish.

    env:
      PACK_VERSION: 0.17.0

    steps:
      - name: Defaults
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.pack-version }}" != "" ]]; then
            echo PACK_VERSION="${{ github.event.inputs.pack-version }}" >> $GITHUB_ENV
          fi
          REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          echo REPOSITORY_NAME="$REPOSITORY_NAME" >> $GITHUB_ENV
          echo CONTAINER_IMAGE=$(echo "gcr.io/${{ secrets.GCR_PROJECT }}/actions/${REPOSITORY_NAME}:${{ github.sha }}") >> $GITHUB_ENV

      - name:  Install pack CLI
        shell: bash
        run:   |
           #!/usr/bin/env bash
           set -euo pipefail
           mkdir -p "${HOME}"/bin
           echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
           echo "Installing pack ${PACK_VERSION}"
           curl \
             --show-error \
             --silent \
             --location \
             "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" \
           | tar -C "${HOME}/bin" -xz pack

      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Pack Build
        run: pack build --builder=gcr.io/buildpacks/builder $REPOSITORY_NAME

      - name: Docker Tag and Push
        run: |
          docker tag $REPOSITORY_NAME $CONTAINER_IMAGE
          docker push $CONTAINER_IMAGE
          echo $REPOSITORY_NAME - Built and Published $CONTAINER_IMAGE
