name: CI for Node.js

on:
  push:                   # Pushes to main.
    branches: [ 'main' ]  
  pull_request:           # PRs to main.
    branches: [ 'main' ]
  workflow_dispatch:      # Manual trigger.
    inputs:
      pack-version:
        description: 'The version of pack to install'

jobs:

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  push_to_registry:
    if: github.event_name == 'push'
    name: Build Container and Push
    runs-on: ubuntu-latest
    needs: test           # depends on jobs.test to finish.

    env:
      PACK_VERSION: 0.17.0

    steps:
      - name: Defaults
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.pack-version }}" != "" ]]; then
            echo "PACK_VERSION=${{ github.event.inputs.pack-version }}" >> $GITHUB_ENV
          fi
          REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')
          echo REPOSITORY_NAME="$REPOSITORY_NAME" >> $GITHUB_ENV
          echo CONTAINER_IMAGE=$(echo "gcr.io/${{ secrets.GCR_PROJECT }}/actions/${REPOSITORY_NAME}:${{ github.sha }}"

      - name:  Install pack CLI
        shell: bash
        run:   |
           #!/usr/bin/env bash
           set -euo pipefail
           mkdir -p "${HOME}"/bin
           echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
           echo "Installing pack ${PACK_VERSION}"
           curl \
             --show-error \
             --silent \
             --location \
             "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" \
           | tar -C "${HOME}/bin" -xz pack

      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Pack Build
        run: pack build --builder=gcr.io/buildpacks/builder $REPOSITORY_NAME

      - name: Docker Tag and Push
        run: |
          docker tag learning-nc $CONTAINER_IMAGE
          docker push $CONTAINER_IMAGE

      - name: Image digest
        run: echo $REPOSITORY_NAME - Built and Published $CONTAINER_IMAGE
