name: Publish Docker image
on:
  push:
    branches:          # Push to main.
      - 'main'

  workflow_dispatch:   # Manual trigger.
    inputs:
      pack-version:
        description: 'The version of pack to install'

jobs:
  push_to_registry:
    name: Push pack built image to GCR.
    runs-on: ubuntu-latest

    env:
      PACK_VERSION: 0.17.0
    
    steps:
      - name: Defaults
        shell: bash
        run: |
          if [[ "${{ github.event.inputs.pack-version }}" != "" ]]; then
            echo "PACK_VERSION=${{ github.event.inputs.pack-version }}" >> $GITHUB_ENV
          fi
          echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}') >> $GITHUB_ENV

      - name:  Install pack CLI
        shell: bash
        run:   |
           #!/usr/bin/env bash
           set -euo pipefail
           mkdir -p "${HOME}"/bin
           echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
           echo "Installing pack ${PACK_VERSION}"
           curl \
             --show-error \
             --silent \
             --location \
             "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" \
           | tar -C "${HOME}/bin" -xz pack

      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Check out the repo
        uses: actions/checkout@v2

      # TODO: run the unit tests here

      - name: Pack Build
        run: |
          pack build --builder=gcr.io/buildpacks/builder learning-nc

      - name: Docker Push
        env:
          CONTAINER_IMAGE: gcr.io/${{ secrets.GCR_PROJECT }}/learning-nc:${{ github.sha }}
        run: |
          docker tag learning-nc $CONTAINER_IMAGE
          docker push $CONTAINER_IMAGE
          
          echo CONTAINER_IMAGE=$(echo "$CONTAINER_IMAGE") >> $GITHUB_ENV

      - name: Image digest
        run: |
          echo $REPOSITORY_NAME - Built and Published $CONTAINER_IMAGE
