name: Publish Docker image
on:
  push:
    branches:
      - 'main'

inputs:
  pack-version:
    description: 'The version of pack to install'
    required:    false
    default:     '0.17.0'

jobs:
  push_to_registry:
    name: Push Docker image to GitHub Container Registry
    runs-on: ubuntu-latest
    steps:
      - run: echo ::set-env name=REPOSITORY_NAME::$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}')

      - name:  Install pack CLI
        shell: bash
        run:   |
           #!/usr/bin/env bash
           set -euo pipefail
           mkdir -p "${HOME}"/bin
           echo "PATH=${HOME}/bin:${PATH}" >> "${GITHUB_ENV}"
           PACK_VERSION=${{ inputs.pack-version }}
           echo "Installing pack ${PACK_VERSION}"
           curl \
             --show-error \
             --silent \
             --location \
             "https://github.com/buildpacks/pack/releases/download/v${PACK_VERSION}/pack-v${PACK_VERSION}-linux.tgz" \
           | tar -C "${HOME}/bin" -xz pack

      - name: Login to Google Cloud Registry
        uses: docker/login-action@v1
        with:
          registry: gcr.io
          username: _json_key
          password: ${{ secrets.GCR_JSON_KEY }}

      - name: Check out the repo
        uses: actions/checkout@v2

      # TODO: run the unit tests here

      - name: Pack Build
        run: |
          pack build --builder=gcr.io/buildpacks/builder learning-nc

      - name: Docker Push
        env:
          CONTAINER_IMAGE: docker tag learning-node gcr.io/${{ secrets.GCR_PROJECT }}/learning-nc:${{ github.sha }}
        run: |
          docker tag learning-nc $CONTAINER_IMAGE
          docker push $CONTAINER_IMAGE
          
          echo ::set-env name=CONTAINER_IMAGE::$(echo "$CONTAINER_IMAGE")

      - name: Image digest
        run: |
          echo $REPOSITORY_NAME - Built and Published $CONTAINER_IMAGE
